DROP TABLE IF EXISTS peeps;
DROP SEQUENCE IF EXISTS peeps_id_seq;

CREATE SEQUENCE IF NOT EXISTS peeps_id_seq;
CREATE TABLE peeps (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255),
    content VARCHAR(255),
    date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
